<?php
/**
 * Copyright ETS Software Technology Co., Ltd
 *
 * NOTICE OF LICENSE
 *
 * This file is not open source! Each license that you purchased is only available for 1 website only.
 * If you want to use this file on more websites (or projects), you need to purchase additional licenses.
 * You are not allowed to redistribute, resell, lease, license, sub-license or offer our resources to any third party.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future.
 *
 * @author ETS Software Technology Co., Ltd
 * @copyright  ETS Software Technology Co., Ltd
 * @license    Valid for 1 website (or project) for each purchase of license
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

require_once(_PS_MODULE_DIR_ . 'ets_cfultimate/classes/ETS_CFU_Pagination.php');

class AdminContactFormUltimateMessageController extends ModuleAdminController
{
    public $is170 = false;

    public function __construct()
    {
        parent::__construct();
        $this->bootstrap = true;
        if (Ets_cfultimate::checkVersionPs('1.7.0', '>=')) {
            $this->is170 = true;
        }
    }

    public function setMedia($isNewTheme = false)
    {
        Media::addJsDef([
            'ETS_CFU_ATTACHMENT_MAX_FILES' => ETS_CFU_Tools::getPostMaxSizeBytes(),
        ]);
        parent::setMedia($isNewTheme); // TODO: Change the autogenerated stub
    }

    public function initContent()
    {
        parent::initContent();
        if (Tools::isSubmit('etsCfuSubmitSpecialActionMessage') && ($id_message = Tools::getValue('id_contact_message'))) {
            $messages = array();
            ETS_CFU_Contact_Message::updateSpecial($id_message, (int)Tools::getValue('special') > 0 ? 0 : 1);
            $messages[$id_message] = htmlentities($this->displayRowMessage($id_message));
            die(json_encode(array(
                'ok' => true,
                'messages' => $messages,
                'msg' => sprintf($this->l('Mark #%s message as special successfully.'), $id_message)
            )));
        }

        if (Tools::isSubmit('etsCfuSubmitBulkActionMessage')) {
            $bulk_action_message = Tools::getValue('bulk_action_message');
            if ($bulk_action_message && Tools::getValue('etsCfuMessageReaded')) {
                if ($bulk_action_message == 'mark_as_read') {
                    $messages = array();
                    foreach (Tools::getValue('etsCfuMessageReaded') as $key => $value) {
                        ETS_CFU_Contact_Message::updateIsRead($key);
                        unset($value);
                        $messages[$key] = $this->displayRowMessage($key);
                    }
                    die(
                    json_encode(
                        array(
                            'ok' => true,
                            'messages' => $messages,
                            'count_messages' => ETS_CFU_Contact_Message::getCountUnreadMessage(),
                        )
                    )
                    );

                } elseif ($bulk_action_message == 'mark_as_unread') {
                    $messages = array();
                    foreach (Tools::getValue('etsCfuMessageReaded') as $key => $value) {
                        ETS_CFU_Contact_Message::updateIsRead($key, 0);
                        unset($value);
                        $messages[$key] = $this->displayRowMessage($key);
                    }
                    die(
                    json_encode(
                        array(
                            'ok' => true,
                            'messages' => $messages,
                            'count_messages' => ETS_CFU_Contact_Message::getCountUnreadMessage(),
                        )
                    )
                    );

                } elseif ($bulk_action_message == 'delete_selected') {
                    foreach (Tools::getValue('etsCfuMessageReaded') as $key => $value) {
                        $attachments = ETS_CFU_Contact_Message::getAttachmentsMessagesByIdContactMessage($key);
                        if ($attachments) {
                            foreach (explode(',', $attachments) as $attachment) {
                                $filename = _PS_DOWNLOAD_DIR_ . $this->module->name . DIRECTORY_SEPARATOR . $attachment;
                                if (file_exists($filename))
                                    @unlink($filename);
                            }
                        }
                        ETS_CFU_Contact_Message::deleteByIdContactMessage($key);
                        unset($value);
                    }
                    die(
                    json_encode(
                        array(
                            'ok' => true,
                            'url_reload' => $this->context->link->getAdminLink('AdminContactFormUltimateMessage', true) . '&conf=1'
                        )
                    )
                    );
                }
            }
        }
        //reply message.
        if (Tools::isSubmit('etsCfuSubmitReplyMessage') && $id_message = Tools::getValue('id_message')) {
            $reply = new ETS_CFU_Contact_Reply();
            $errors = array();
            $context = Context::getContext();
            $template = Configuration::get('ETS_CFU_ENABLE_TEMPLATE') ? 'contact_reply_form_ultimate' : 'contact_reply_form_ultimate_plain';
            $configuration = Configuration::getMultiple(
                array(
                    'PS_SHOP_EMAIL',
                    'PS_SHOP_NAME',
                    'PS_MAIL_TYPE',
                ),
                null,
                null, $context->shop->id
            );
            if (!Tools::getValue('reply_to')) {
                $errors[] = $this->module->l('Reply to is required');
            }
            if (!Tools::getValue('reply_subject')) {
                $errors[] = $this->module->l('Subject is required');
            }
            if (!Tools::getValue('message_reply')) {
                $errors[] = $this->module->l('Message is required');
            }
            if (!Ets_CfUltimate::getEmailToString(Tools::getValue('reply_to'))) {
                $errors[] = $this->module->l('Email is not validate');
            }
            $this->module->validateUpload('attachment'
                , ['label' => $this->l('Attachment')]
                , _PS_DOWNLOAD_DIR_ . $this->module->name . DIRECTORY_SEPARATOR
                , $errors
                , ['jpg', 'jpeg', 'png', 'gif', 'zip', 'pdf']
            );
            if (!$errors) {
                $mail_temp = $this->module->getLocalPath() . 'mails/' . $context->language->iso_code . '/' . $template;
                $msg = $this->module->l('Error - The following e-mail template is missing: %s');
                if (!file_exists(($file = $mail_temp . '.txt')) && ($configuration['PS_MAIL_TYPE'] == Mail::TYPE_BOTH || $configuration['PS_MAIL_TYPE'] == Mail::TYPE_TEXT)) {
                    $errors[] = sprintf($msg, $file);
                } else if (!file_exists(($file = $mail_temp . '.html')) && ($configuration['PS_MAIL_TYPE'] == Mail::TYPE_BOTH || $configuration['PS_MAIL_TYPE'] == Mail::TYPE_HTML)) {
                    $errors[] = sprintf($msg, $file);
                }
            }

            if ($errors) {
                die(json_encode(array(
                    'error' => $this->module->displayError($errors),
                )));
            } else {
                $file = $_FILES['attachment'] ?? null;
                $filename = null;
                if ($file) {
                    $uploads_dir = ets_cfu_upload_tmp_dir();
                    $filename = $file['name'];
                    $filename = ets_cfu_canonicalize($filename, 'as-is');
                    $filename = ets_cfu_antiscript_file_name($filename);
                    $filename = ets_cfu_generateRandomString(7) . '-' . ets_cfu_unique_filename($uploads_dir, str_replace(' ', '-', $filename));
                    $new_file = ets_cfu_path_join($uploads_dir, $filename);
                    if (false === move_uploaded_file($file['tmp_name'], $new_file)) {
                        $filename = null;
                    }
                }
                $attachment = null;
                if ($filename !== null && @file_exists(_PS_DOWNLOAD_DIR_ . $this->module->name . DIRECTORY_SEPARATOR . $filename)) {
                    $context->smarty->assign([
                        'send_mail_file_attachment' => $context->link->getModuleLink($this->module->name, 'download', ['file' => $filename]),
                        'send_mail_file_attachment_title' => $filename,
                    ]);
                    $attachment = $context->smarty->fetch($this->module->getLocalPath() . 'views/templates/hook/attachment.tpl');
                }
                $template_email = Configuration::get('ETS_CFU_EMAIL_REPLY_TEMPLATE', Context::getContext()->language->id);
                $template_vars = array(
                    '{message_content}' => Configuration::get('ETS_CFU_ENABLE_TEMPLATE') ? str_replace(
                        array('{message_content}', '%7Bshop_url%7D', '%7Bshop_logo%7D', '{shop_logo}'),
                        array(Tools::getValue('message_reply') . ($attachment !== null ? $attachment : ''), '{shop_url}', '{shop_logo}', preg_replace('/<!--(.*)-->/Uis', '', $context->smarty->fetch($this->module->getLocalPath() . 'views/templates/hook/shop_logo.tpl'))),
                        $template_email
                    ) : Tools::getValue('message_reply'),
                );
                $toEmail = Ets_CfUltimate::getEmailToString(Tools::getValue('reply_to'));
                $toName = str_replace(array('<', '>', $toEmail), '', Tools::getValue('reply_to'));
                $fromEmail = Ets_CfUltimate::getEmailToString(Tools::getValue('from_reply'));
                $fromName = str_replace(array('<', '>', $fromEmail), '', Tools::getValue('from_reply'));
                $replyTo = Ets_CfUltimate::getEmailToString(Tools::getValue('reply_to_reply'));
                $replyToName = trim(str_replace(array('<', '>', $replyTo), '', Tools::getValue('reply_to_reply')));

                if (Mail::Send(
                    Context::getContext()->language->id,
                    $template,
                    Tools::getValue('reply_subject'),
                    $template_vars,
                    $toEmail,
                    $toName ? $toName : null,
                    $fromEmail ? $fromEmail : null,
                    $fromName ? $fromName : null,
                    null,
                    null,
                    $this->module->getLocalPath() . 'mails/',
                    false,
                    Context::getContext()->shop->id,
                    null,
                    $replyTo ? $replyTo : null,
                    $replyToName ? $replyToName : null
                )) {
                    $reply->id_contact_message = $id_message;
                    $reply->content = Tools::getValue('message_reply');
                    $reply->id_employee = $this->context->employee->id;
                    $reply->reply_to = Tools::getValue('reply_to');
                    $reply->subject = Tools::getValue('reply_subject');
                    $reply->attachment = $filename;
                    if (trim($reply->attachment) !== '')
                        $reply->attachment_file = $context->link->getAdminLink('AdminContactFormUltimateDownload', true, [], ['file' => $filename]);
                    $reply->add();
                    die(json_encode(array(
                        'success' => $this->module->l('Your message has been successfully sent'),
                        'message_reply' => Tools::getValue('message_reply'),
                        'id_message' => $id_message,
                        'reply' => $this->module->displayReplyMessage($reply),
                    )));
                } else {
                    $errors[] = $this->module->l('An error occurred while sending the message');
                    die(json_encode(array(
                        'error' => $this->module->displayError($errors),
                    )));
                }
            }
        }

        if (Tools::isSubmit('etsCfuDeleteMessage') && $id_message = Tools::getValue('id_message')) {
            $attachments = ETS_CFU_Contact_Message::getAttachmentsMessagesByIdContactMessage($id_message);
            if ($attachments) {
                foreach (explode(',', $attachments) as $attachment) {
                    $filename = _PS_DOWNLOAD_DIR_ . $this->module->name . DIRECTORY_SEPARATOR . $attachment;
                    if (file_exists($filename))
                        @unlink($filename);
                }
            }
            ETS_CFU_Contact_Message::deleteAllByIdContactMessage($id_message);
            Tools::redirectAdmin($this->context->link->getAdminLink('AdminContactFormUltimateMessage', true) . '&conf=1');
        }

        if (Tools::isSubmit('etsCfuAjax') && Tools::isSubmit('etsCfuViewMessage') && $id_message = Tools::getValue('id_message')) {
            $message = ETS_CFU_Contact_Message::getMessageByIdContactMessage($id_message, $this->context);
            if ($message['reply_to'] && Ets_CfUltimate::getEmailToString($message['reply_to'])) {
                $message['reply_to_check'] = true;
            } else
                $message['reply_to_check'] = false;
            if ($message) {
                $replies = ETS_CFU_Contact_Message::getRepliesByIdContactMessage($id_message, $this->context);
                $this->context->smarty->assign(array(
                    'message' => $message,
                    'replies' => $replies,
                    'is170' => $this->is170,
                    'download_url' => $this->module->getDownloadLink(),
                    'ETS_CFU_POST_MAX_SIZE' => ETS_CFU_Tools::formatBytes(ETS_CFU_Tools::getPostMaxSizeBytes())
                ));
                $message_html = $this->module->display(_PS_MODULE_DIR_ . $this->module->name . DIRECTORY_SEPARATOR . $this->module->name . '.php', 'message.tpl');

                if (!Validate::isCleanHtml($message_html, true)) {
                    die(json_encode(array(
                        'errors' => $this->module->l('Message invalid.'),
                    )));
                }
                $messages = array();
                if (!Tools::getValue('etsCfuMessageReaded')) {
                    ETS_CFU_Contact_Message::updateIsRead($id_message);
                    $messages[$id_message] = $this->displayRowMessage($id_message);
                }
                die(json_encode(array(
                    'message_html' => $message_html,
                    'messages' => $messages,
                    'count_messages' => ETS_CFU_Contact_Message::getCountUnreadMessage(),
                )));
            }
        }
    }

    public function displayRowMessage($message)
    {
        if (!is_array($message) && Validate::isUnsignedInt($message))
            $message = ETS_CFU_Contact_Message::getMessageByIdContactMessage($message, $this->context);
        if (!$message)
            return '';
        $this->context->smarty->assign(array(
            'message' => $message,
        ));
        return $this->context->smarty->fetch($this->module->getLocalPath() . 'views/templates/hook/row-message.tpl');
    }

    public function renderList()
    {
        if (!$this->module->active) {
            return $this->module->displayWarning($this->l('You must enable "Contact Form Ultimate" module to configure its features'));
        }
        if (Tools::isSubmit('etsCfuViewMessage') && $id_message = Tools::getValue('id_message')) {
            $message = ETS_CFU_Contact_Message::getMessageByIdContactMessage($id_message, $this->context);
            if ($message['reply_to'] && Ets_CfUltimate::getEmailToString($message['reply_to'])) {
                $message['reply_to_check'] = True;
            } else
                $message['reply_to_check'] = false;
            if ($message) {
                $replies = ETS_CFU_Contact_Message::getRepliesByIdContactMessage($id_message, $this->context);
                $this->context->smarty->assign(
                    array(
                        'message' => $message,
                        'replies' => $replies,
                        'base_url' => $this->module->getBaseLink(),
                        'is170' => $this->is170,
                        'download_url' => $this->module->getDownloadLink()
                    )
                );
                return $this->module->display(_PS_MODULE_DIR_ . $this->module->name . DIRECTORY_SEPARATOR . $this->module->name . '.php', 'message.tpl');
            }
        } else {
            $filter = '';
            $values_submit = array();
            $id_contact = trim(Tools::getValue('id_contact'));
            if ($id_contact !== '' && Validate::isUnsignedInt($id_contact) && (int)$id_contact > 0) {
                $filter .= ' AND m.id_contact="' . (int)$id_contact . '"';
                $values_submit['id_contact'] = (int)$id_contact;
            }
            $id_contact_message = trim(Tools::getValue('id_contact_message'));
            if ($id_contact_message !== '' && Validate::isUnsignedInt($id_contact_message) && (int)$id_contact_message > 0) {
                $filter .= ' AND m.id_contact_message="' . (int)$id_contact_message . '"';
                $values_submit['id_contact_message'] = (int)$id_contact_message;
            }
            $subject = trim(Tools::getValue('subject'));
            if ($subject !== '' && Validate::isCleanHtml($subject)) {
                $filter .= ' AND m.subject like "%' . pSQL($subject) . '%"';
                $values_submit['subject'] = $subject;
            }
            $sender = trim(Tools::getValue('sender'));
            if ($sender !== '' && Validate::isCleanHtml($sender)) {
                $filter .= ' AND m.sender like "%' . pSQL($sender) . '%"';
                $values_submit['sender'] = $sender;
            }
            $dateAddFrom = trim(Tools::getValue('messageFilter_dateadd_from'));
            if ($dateAddFrom !== '' && Validate::isDate($dateAddFrom)) {
                $filter .= ' AND m.date_add >="' . pSQL($dateAddFrom) . '"';
                $values_submit['messageFilter_dateadd_from'] = $dateAddFrom;
            }
            $dateAddTo = trim(Tools::getValue('messageFilter_dateadd_to'));
            if ($dateAddTo !== '' && Validate::isDate($dateAddTo)) {
                $filter .= ' AND m.date_add <= "' . pSQL($dateAddTo) . '"';
                $values_submit['messageFilter_dateadd_to'] = $dateAddTo;
            }
            $replied = trim(Tools::getValue('messageFilter_replied'));
            if ($replied !== '' && Validate::isUnsignedInt($replied)) {
                if ((int)$replied == 0)
                    $filter .= ' AND m.id_contact_message NOT IN (SELECT id_contact_message FROM ' . _DB_PREFIX_ . 'ets_cfu_message_reply)';
                else
                    $filter .= ' AND m.id_contact_message IN (SELECT id_contact_message FROM ' . _DB_PREFIX_ . 'ets_cfu_message_reply)';
                $values_submit['messageFilter_replied'] = (int)$replied;
            }
            $message = trim(Tools::getValue('messageFilter_message'));
            if ($message !== '' && Validate::isCleanHtml($message)) {
                $filter .= ' AND m.body like "%' . pSQL($message) . '%"';
                $values_submit['messageFilter_message'] = $message;
            }
            $url_extra_no_order = http_build_query($values_submit);

            $orderBy = trim(Tools::getValue('OrderBy'));
            if ($orderBy === '' || !Validate::isOrderBy($orderBy))
                $orderBy = 'm.id_contact_message';
            $values_submit['OrderBy'] = $orderBy;

            $orderWay = trim(Tools::getValue('OrderWay'));
            if ($orderWay === '' || !Validate::isOrderWay($orderWay))
                $orderWay = 'DESC';
            $values_submit['OrderWay'] = $orderWay;

            $sortBy = $orderBy . ' ' . $orderWay . ($orderBy !== 'm.id_contact_message' ? ', m.id_contact_message DESC' : '');
            $totalMessage = ETS_CFU_Contact_Message::getMessageList($filter, 0, 0, true, $sortBy);
            $limit = (int)Tools::getValue('paginator_message_select_limit', 20);
            $page = (int)Tools::getValue('page', 1);
            $start = ($page - 1) * $limit;
            $pagination = new ETS_CFU_Pagination();
            $pagination->url = $this->context->link->getAdminLink('AdminContactFormUltimateMessage') . '&' . http_build_query($values_submit) . '&page=_page_' . ($limit ? '&paginator_message_select_limit=' . $limit : '');
            $pagination->limit = $limit;
            $pagination->page = $page;
            $pagination->total = $totalMessage;
            $pagination->controller = Tools::getValue('controller');
            if (Tools::isSubmit('etsCfuSubmitExportButtonMessage')) {
                ob_get_clean();
                ob_start();
                $messages = ETS_CFU_Contact_Message::getMessageList($filter, $start, $limit, false, $sortBy);
                $csv = "Subject\tFrom\tContact Form\tMessage\tDate" . "\r\n";
                foreach ($messages as $row) {
                    $message = array();
                    $message[] = $row['subject'];
                    $message[] = $row['sender'];
                    $message[] = $row['title'];
                    $message[] = str_replace("\n", '', strip_tags($row['body']));
                    $message[] = $row['date_add'];
                    $csv .= join("\t", $message) . "\r\n";
                }
                $csv = chr(255) . chr(254) . mb_convert_encoding($csv, "UTF-16LE", "UTF-8");
                header("Content-type: application/x-msdownload");
                header("Content-disposition: csv; filename=" . date("Y-m-d") .
                    "_message_list.csv; size=" . Tools::strlen($csv));
                echo $csv;
                exit();
            }
            $messages = ETS_CFU_Contact_Message::getMessageList($filter, $start, $limit, false, $sortBy);
            if ($messages) {
                foreach ($messages as &$message) {
                    $message['replies'] = ETS_CFU_Contact_Message::getRepliesByIdContactMessage($message['id_contact_message'], $this->context);
                    $message['row_message'] = $this->displayRowMessage($message);
                }
            }
            $contacts = ETS_CFU_Contact::getContactList();
            $this->context->smarty->assign(
                array(
                    'totalMessage' => $totalMessage,
                    'messages' => $messages,
                    'ets_cfu_contacts' => $contacts,
                    'url_module' => $this->context->link->getAdminLink('AdminModules') . '&configure=' . $this->module->name . '&tab_module=' . $this->module->tab . '&module_name=' . $this->module->name,
                    'link' => $this->context->link,
                    'base_url' => $this->module->getBaseLink(),
                    'filter' => $filter,
                    'is_ps15' => (bool)version_compare(_PS_VERSION_, '1.6', '<'),
                    'ets_cfu_pagination_text' => $pagination->render(),
                    'values_submit' => $values_submit,
                    'url_full' => $this->context->link->getAdminLink('AdminContactFormUltimateMessage') . '&' . $url_extra_no_order . '&page=' . Tools::getValue('page', 1) . ($pagination->limit ? '&paginator_message_select_limit=' . $pagination->limit : ''),
                    'orderBy' => Tools::getValue('OrderBy', 'm.id_contact_message'),
                    'orderWay' => Tools::getValue('OrderWay', 'DESC'),
                    'paginator_per_page' => array(
                        5 => 5,
                        20 => 20,
                        50 => 50,
                        100 => 100,
                        1000 => 1000,
                    ),
                    'selected_per_page' => $limit,
                )
            );
            return $this->context->smarty->fetch($this->module->getLocalPath() . 'views/templates/hook/list-message.tpl');
        }
    }
}