<?php

/**
 * File from https://prestashow.pl
 *
 * DISCLAIMER
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future.
 *
 * @authors     PrestaShow.pl <kontakt@prestashow.pl>
 * @copyright   2019 PrestaShow.pl
 * @license     https://prestashow.pl/license
 */

if (!class_exists('PShowFbReviews')) {
    require_once dirname(__FILE__) . "/config.php";
    
    class PShowFbReviews extends \Prestashow\PShowFbReviews\Model\Module
    {
        
    }
}
//$this->l('Hooks')
//$this->l('Hooks')
//$this->l('Delete this hook?')
//$this->l('Hooks')
//$this->l('ID')
//$this->l('Hook name')
//$this->l('Hook add error, try again')
//$this->l('Edit hook')
//$this->l('Hook')
//$this->l('Hook')
//$this->l('Save')
//$this->l('Any reviews')
//$this->l('Poor')
//$this->l('Fair')
//$this->l('Good')
//$this->l('Very Good')
//$this->l('Excellent')
//$this->l('Settings')
//$this->l('Settings')
//$this->l('Settings')
//$this->l('Saved successfully.')
//$this->l('Settings')
//$this->l('Please add the following address to the cron')
//$this->l('RECOMENDED: If you disable CRON option your shop will be load slower')
//$this->l('Settings')
//$this->l('Settings')
//$this->l('Enable sending events to Facebook')
//$this->l('Enable or disable FaceBook Pixel conversions in the store')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Select the tracking method')
//$this->l('Select the method of sending events to Facebook Pixel')
//$this->l('Facebook Conversion API (PHP) - domyślnie')
//$this->l('Facebook Pixel (JavaScript)')
//$this->l('Facebook Conversion API (PHP) and Facebook Pixel (JavaScript)')
//$this->l('Access token Conversion API')
//$this->l('FaceBook Pixel Id')
//$this->l('Select the order statuses after which the order should be sent to fb pixel')
//$this->l('Send hashed personal data of customers')
//$this->l('This will increase the quality indicators of event matching')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Use alternate hook to handle orders.')
//$this->l('This function should be enabled only if the template in the store uses elementor, or orders are not sent to fb pixel despite the correct configuration.')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Send all events using CRON.')
//$this->l('RECOMENDED: Events will be sent with orders using CRON job. If you disable this option your shop will be load slower.')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Save')
//$this->l('Fold menu after entering the module')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Show tips')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Print info about module')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Logging level')
//$this->l('In production you should use "Warning" or higher.')
//$this->l('Debug')
//$this->l('Info')
//$this->l('Notice')
//$this->l('Warning')
//$this->l('Error')
//$this->l('Critical')
//$this->l('Settings')
//$this->l('Settings')
//$this->l('Settings')
//$this->l('To update the list of reviews, please visit')
//$this->l('You could use this link to configure CRON.') ); } public function postProcess() { if (Tools::isSubmit('submitSaveConfiguration')
//$this->l('Saved successfully.')
//$this->l('Settings')
//$this->l('Settings')
//$this->l('Settings')
//$this->l('FaceBook App Id')
//$this->l('FaceBook App Secret Key')
//$this->l('FaceBook App access token')
//$this->l('FaceBook Fanpage ID')
//$this->l('Title')
//$this->l('Invalid characters:')
//$this->l('Title of page with reviews')
//$this->l('Invalid characters:')
//$this->l('Friendly URL')
//$this->l('Only letters and the minus (-) character are allowed.')
//$this->l('Pull-out side panel')
//$this->l('Shows or hides the pull-out side panel')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Display page with reviews')
//$this->l('Shows or hides the page with reviews')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Display only positive reviews')
//$this->l('Shows or hides negative reviews')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Display reviews')
//$this->l('Shows or hides the reviews')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Enabled reviews as stars')
//$this->l('Shows or hides the reviews as stars')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Display Facebook "like it" button')
//$this->l('Show or hide the Facebook "like it" button')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Star color when enabled')
//$this->l('Enter hex code.')
//$this->l('Star color when disabled')
//$this->l('Enter hex code.')
//$this->l('Bar color in progressbar')
//$this->l('Enter hex code.')
//$this->l('Progressbar color')
//$this->l('Enter hex code.')
//$this->l('Save')
//$this->l('Hooks')
//$this->l('Hooks')
//$this->l('Delete this hook?')
//$this->l('Hooks')
//$this->l('ID')
//$this->l('Hook name')
//$this->l('Hook add error, try again')
//$this->l('Edit hook')
//$this->l('Hook')
//$this->l('Hook')
//$this->l('Save')
//$this->l('Facebook Integrator')
//$this->l('Module allow display recommendations from page on facebook.')
//$this->l('Any reviews')
//$this->l('Poor')
//$this->l('Fair')
//$this->l('Good')
//$this->l('Very Good')
//$this->l('Excellent')